services:
  db:
    image: mysql:8.0
    container_name: otp-db
    command:
      - "--innodb-buffer-pool-size=2G"
      - "--skip-ssl"
      - "--max-connections=1000"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: db
      MYSQL_DATABASE: db
    volumes:
      - ./data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
      - /run/mysqld/:/run/mysqld/
    ports:
      - 3306:3306
    logging:
      driver: "json-file"
      options:
        max-size: "250M"
        max-file: "3"
  app:
    image: rest-otp-app
    build: .
    restart: always
    container_name: otp-app
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - ../src:/root/src
    environment:
      DB_HOST: otp-db
    logging:
      driver: "json-file"
      options:
        max-size: "250M"
        max-file: "3"
