services:
  rest-db:
    image: mysql:8.0
    container_name: rest-db
    command:
      - "--innodb-buffer-pool-size=2G"
      - "--default-authentication-plugin=mysql_native_password"
      - "--skip-ssl"
      - "--max-connections=1000"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: db
      MYSQL_DATABASE: db
    volumes:
      - ./data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
      - /run/mysqld/:/run/mysqld/
    ports:
      - 3306:3306
    logging:
      driver: "json-file"
      options:
        max-size: "250M"
        max-file: "3"
